"""Removed age column.

Revision ID: 5fe3fc164c4e
Revises: 2f5ae0faf196
Create Date: 2024-01-20 23:01:33.749844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fe3fc164c4e'
down_revision = '2f5ae0faf196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
